version: 2.1

orbs:
  node: circleci/node@5.1.0
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout

      # Install backend dependencies
      - run:
          name: Install Backend
          command: cd backend && npm ci

      # Run backend tests (now using in-memory MongoDB â†’ will pass)
      - run:
          name: Run Backend Tests
          command: cd backend && npm test

     # Skip frontend testing entirely
      - run:
         name: Skip frontend tests
         command: echo "No frontend tests to run."


    sonar_scan:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run: npm ci --prefix backend
      - sonarcloud/scan


workflows:
  main:
    jobs:
      - build_and_test
      - sonar_scan:
          requires:
            - build_and_test
